### ISSUE TITLE
Ms Treatment Session ends when initially lying down

### ISSUE THREAD

**Issue by kisatan** [deviant-dev/dominatrix-simulator-issues#245] opened 2022-09-19 03:10 UTC
**Describe the bug**
When doing a session with Ms Treatment and choosing to lay down the session ends immediately.

**To Reproduce**
1. Go to Ms Treatments room
2. Choose session
3. Lay down
4. Session ends

**Expected behavior**
The session should continue even when choosing to lie down.

**System Info(please complete the following information):**
 - VR Device: Meta Quest 2
 - Version: Dominatrix Simulator v.2.4.1+165@99c8b22

**Additional context**
The problem does not occur in the standalone version (DS Devil Girl Therapy v.2.1.0+19@be94d3d).

**Logs**
DomSim: https://pastebin.com/AKy61SMa 
Standalone: https://pastebin.com/4sZqBxjY

**Comment by Sonny3412** [comment] 2023-01-26 04:29
Hello,

I tried to reproduce it but the game doesn't crash, that's a problem of the room area you selected for your Quest 2! 

System info I reproduced it on: 
- Oculus Quest 2 with Air Link plugged to my PC (1070 GTX, i5 8600k, 16gb ddr4 3200mhz)
![Screenshot )](https://user-images.githubusercontent.com/123605940/214758825-46341b1c-31f7-4bff-a5a8-8a829b3b36f0.png)

**Comment by ThatCuteEevee** [comment] 2023-02-10 21:59
Sonny was unable to reproduce the issue, closing issue

**Closed as completed by ThatCuteEevee** 2023-02-10 21:59 UTC
Labels: Gameplay Bug
