### ISSUE TITLE
Ms T Therapy Submissive Headspace

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/dominatrix-simulator-issues#173] opened 2021-06-11 21:35 UTC
**Describe the bug**
Need to reduce room echo.
Suggest adding in quiet rythmic breathing sounds, to help the player get into a meditative state.
When Ms T says "Listen to the sound of my voice. Feel my words surround you like a warm, soothing blanket.", suggest that there is an additional audio source at the players location, to make it feels like she's literally getting inside your head.

**System Info:**
 - VR Device: HTC Vive 1st Gen
 - Version: 2.1.0+143

**Comment by deviant-dev** [comment] 2021-06-13 04:18
I've reduced the room echo. Additional submission features like breathing and headspace VO will take more time and should be broken out as separate feature requests.

**Comment by HeadphoneTaco** [comment] 2021-06-15 02:43
Sounds good, those will be nice touches, but not needed at this time.

**Comment by ThatCuteEevee** [comment] 2021-07-19 18:27
Confirmed issue with echo has been greatly reduced in 2.1.0+145. Since suggestions will be spun off into feature requests closing this case

**Closed as completed by ThatCuteEevee** 2021-07-19 18:27 UTC
Labels: Ink, Audio
