### ISSUE TITLE
All stones removed when loading credits room

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#189] opened 2021-06-28 16:55 UTC
**Describe the bug**
 - When player goes into the credits scene through the credits door with either punishment or reward stones, they are removed without warning

**To Reproduce**
 1) Earn either punishment or reward stones
 2) go into the credits scene and hear the stone removed sound, check wrists and all stones are gone

**Expected behavior**
  - Either the credits scene should not remove stones or the player should be warned it will reset stones

**Screenshots**

**System Info(please complete the following information):**
 - VR Device: Mouse and keyboard
 - Version: 2.1.0 +145

**Additional context**
 - since the player has a chance and is encouraged to explore the different rooms, This is a likely scenario a player may run into where they may have visited other Mistress's and lose progress in stones after going into the credit rooms, forcing them to re-earn the lost stones. Flagging as high priority

**Comment by deviant-dev** [comment] 2021-06-29 08:26
Oh crap! Good catch! 😬

**Comment by rockanrolla** [comment] 2021-09-09 02:10
I can confirm this. I noticed it yesterday but I was unsure of what the exact root cause was. In retrospect, I realize that it occurred just after visiting the credits scene.

**Comment by HeadphoneTaco** [comment] 2021-11-11 19:11
Closing due to lack of further user complaints

**Closed as completed by HeadphoneTaco** 2021-11-11 19:11 UTC
Labels: Gameplay Bug, Help Wanted
