### ISSUE TITLE
Headmistress still out of office

### ISSUE THREAD

**Issue by KingOfEggs** [deviant-dev/dominatrix-simulator-issues#6] opened 2020-02-01 07:05 UTC
**Describe the bug**
The Headmistress is still invisible and mute, though her subtitles work.

**To Reproduce**
Enter the Headmistress' office from the main hall.

**Expected behavior**
For the Headmistress to be disciplining in *physical* form and not as an astral projection

![ruh roh](https://user-images.githubusercontent.com/60536182/73588441-c9ce3280-448e-11ea-8938-3355adb1a752.png)

**System (please complete the following information)**:

- VR Device: K&M
- Win 10 64bit
- Version: #50

**Comment by deviant-dev** [comment] 2020-02-01 21:54
Duplicate of #4

**Closed by deviant-dev** 2020-02-01 21:54 UTC
Labels: bug
