### ISSUE TITLE
Nega Yuki Scene - Soft lock on all blank dice rolls

### ISSUE THREAD

**Issue by ThatCuteEevee** [deviant-dev/dominatrix-simulator-issues#138] opened 2021-05-11 15:10 UTC
**Describe the bug**
 - Reported by tornguitar on steam community page -
    If the player rolls all blanks for the dice roll the player is soft locked, Nega Yuki does not continue the scene if given the lines "wow, that my be the best bad luck I've ever seen. you get nothing of course, but since you've been so good ill let you in on a little secret about the house." then get caption <insert lore here>

**To Reproduce**
 - Play Nega Yuki's dice game
 - roll all blank dice
 - receive the line "wow, that my be the best bad luck I've ever seen. you get nothing of course, but since you've been so good ill let you in on a little secret about the house."

**Expected behavior**
   Nega Yuki should continue the scene and the scene ends without possible soft lock

**Screenshots**
N/A

**System Info(please complete the following information):**
 - VR Device: Mouse and keyboard
 - Version: Current steam version

**Additional context**
  - Validation needed to see if issue occurs on current WIP build
  - Validation that Journal is not a workaround for getting out of soft lock

**Comment by deviant-dev** [comment] 2021-06-12 08:25
This seems to be working fine with the latest.

**Comment by HeadphoneTaco** [comment] 2021-06-24 18:58
Confirmed, closing.

**Closed as completed by HeadphoneTaco** 2021-06-24 18:58 UTC
Labels: Gameplay Bug
